---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home2/a1743bri/public_html/mbco/

    # Copy all files to deployment path
    - /bin/cp -R * $DEPLOYPATH

    # Move into deployment path
    - cd $DEPLOYPATH

    # Install PHP dependencies
    - /usr/local/bin/composer install --no-dev --optimize-autoloader